image: archlinux
packages: 
  - nodejs
  - npm
  - docker
sources:
  - https://git.sr.ht/~erikcraddock/craddock-connection
secrets:
  - 9e43f7a3-cbad-4344-8946-d611e729ea3c
tasks:
  - setup: |
      sudo systemctl enable --now docker
      npm install astro
  - build: |
      cd craddock-connection
      npm install
      npm run build
  - deploy: |
      cd craddock-connection
      export VERSION=$(node -e 'console.log(require("./package.json").version)')
      docker build -t evcraddock/craddock-connection:$VERSION.$JOB_ID -t evcraddock/craddock-connection:latest .
      # docker login -u evcraddock -p $(< ~/.docker-secret)
      # docker push evcraddock/craddock-connection:$VERSION.$JOB_ID
triggers:
  - action: webhook
    condition: success
    url: https://craddock.org:9443/api/webhooks/5f96a2bd-0e0d-4fc2-8c87-1d214a11e600?tag=latest


