image: archlinux
packages:
  - nodejs
  - npm
  - docker
sources:
  - https://git.sr.ht/~erikcraddock/craddock-connection
secrets:
  - 6b4c020e-b1c7-4e4f-9aea-1f2584149be1
  - 0c14aa5c-b6bd-4dec-b8c4-d79bf11ef116
tasks:
  - setup: |
      sudo systemctl enable --now docker

      echo "INSTALL ASTRO"
      npm install astro@latest
  - build: |
      cd craddock-connection
      npm install
      npm run build
  - deploy: |
      cd craddock-connection
      export VERSION=$(node -e 'console.log(require("./package.json").version)')
      docker build -t evcraddock/craddock-connection:$VERSION.$JOB_ID .
      cat ~/.docker-secret | docker login -u evcraddock --password-stdin 
      docker push evcraddock/craddock-connection:$VERSION.$JOB_ID
      curl --insecure -X POST $(<~/.webhook-url)$VERSION.$JOB_ID
