export type newsletter = {
  slug: string;
  title: string;
  author: string;
  publishDate: Date;
  location: string;
  visible: boolean;
};

export const newsletters: newsletter[] = [
  {
    slug: "volume-1-1",
    visible: true,
    title: "Volume 1 Issue 1",
    author: "Ada Morris",
    publishDate: new Date("December 12, 1988"),
    location: "files/newsletters/Volume-1-Issue-01.pdf",
  },
  {
    slug: "volume-1-2",
    visible: true,
    title: "Volume 1 Issue 2",
    author: "Ada Morris",
    publishDate: new Date("January 18, 1989"),
    location: "files/newsletters/Volume-1-Issue-02.pdf",
  },
  {
    slug: "volume-1-3",
    visible: true,
    title: "Volume 1 Issue 3",
    author: "Ada Morris",
    publishDate: new Date("February 28, 1989"),
    location: "files/newsletters/Volume-1-Issue-03.pdf",
  },
  {
    slug: "volume-1-4",
    visible: true,
    title: "Volume 1 Issue 4",
    author: "Ada Morris",
    publishDate: new Date("March 31, 1989"),
    location: "files/newsletters/Volume-1-Issue-04.pdf",
  },
  {
    slug: "volume-1-5",
    visible: true,
    title: "Volume 1 Issue 5",
    author: "Ada Morris",
    publishDate: new Date("April 30, 1989"),
    location: "files/newsletters/Volume-1-Issue-05.pdf",
  },
  {
    slug: "volume-1-6",
    visible: true,
    title: "Volume 1 Issue 6",
    author: "Ada Morris",
    publishDate: new Date("May 30, 1989"),
    location: "files/newsletters/Volume-1-Issue-06.pdf",
  },
  {
    slug: "volume-1-7",
    visible: true,
    title: "Volume 1 Issue 7",
    author: "Ada Morris",
    publishDate: new Date("June 31, 1989"),
    location: "files/newsletters/Volume-1-Issue-07.pdf",
  },
  {
    slug: "volume-1-8",
    visible: true,
    title: "Volume 1 Issue 8",
    author: "Ada Morris",
    publishDate: new Date("July 31, 1989"),
    location: "files/newsletters/Volume-1-Issue-08.pdf",
  },
  {
    slug: "volume-1-9",
    visible: true,
    title: "Volume 1 Issue 9",
    author: "Ada Morris",
    publishDate: new Date("August 31, 1989"),
    location: "files/newsletters/Volume-1-Issue-09.pdf",
  },
  {
    slug: "volume-1-10",
    visible: true,
    title: "Volume 1 Issue 10",
    author: "Ada Morris",
    publishDate: new Date("September 31, 1989"),
    location: "files/newsletters/Volume-1-Issue-10.pdf",
  },
  {
    slug: "volume-1-11",
    visible: true,
    title: "Volume 1 Issue 11",
    author: "Ada Morris",
    publishDate: new Date("October 31, 1989"),
    location: "files/newsletters/Volume-1-Issue-11.pdf",
  },
  {
    slug: "volume-1-12",
    visible: true,
    title: "Volume 1 Issue 12",
    author: "Ada Morris",
    publishDate: new Date("November 30, 1989"),
    location: "files/newsletters/Volume-1-Issue-12.pdf",
  },
  {
    slug: "volume-2-1",
    visible: true,
    title: "Volume 2 Issue 1",
    author: "Ada Morris",
    publishDate: new Date("December 31, 1989"),
    location: "files/newsletters/Volume-2-Issue-01.pdf",
  },
  {
    slug: "volume-2-2",
    visible: true,
    title: "Volume 2 Issue 2",
    author: "Ada Morris",
    publishDate: new Date("January 31, 1990"),
    location: "files/newsletters/Volume-2-Issue-02.pdf",
  },
  {
    slug: "volume-2-3",
    visible: true,
    title: "Volume 2 Issue 3",
    author: "Ada Morris",
    publishDate: new Date("February 28, 1990"),
    location: "files/newsletters/Volume-2-Issue-03.pdf",
  },
  {
    slug: "volume-2-4",
    visible: true,
    title: "Volume 2 Issue 4",
    author: "Ada Morris",
    publishDate: new Date("March 31, 1990"),
    location: "files/newsletters/Volume-2-Issue-04.pdf",
  },
  {
    slug: "volume-2-5",
    visible: true,
    title: "Volume 2 Issue 5",
    author: "Ada Morris",
    publishDate: new Date("April 30, 1990"),
    location: "files/newsletters/Volume-2-Issue-05.pdf",
  },
  {
    slug: "volume-2-6",
    visible: true,
    title: "Volume 2 Issue 6",
    author: "Ada Morris",
    publishDate: new Date("May 31, 1990"),
    location: "files/newsletters/Volume-2-Issue-06.pdf",
  },
  {
    slug: "volume-2-7",
    visible: true,
    title: "Volume 2 Issue 7",
    author: "Ada Morris",
    publishDate: new Date("June 30, 1990"),
    location: "files/newsletters/Volume-2-Issue-07.pdf",
  },
  {
    slug: "volume-2-8",
    visible: true,
    title: "Volume 2 Issue 8",
    author: "Ada Morris",
    publishDate: new Date("July 31, 1990"),
    location: "files/newsletters/Volume-2-Issue-08.pdf",
  },
  {
    slug: "volume-2-9",
    visible: true,
    title: "Volume 2 Issue 9",
    author: "Ada Morris",
    publishDate: new Date("August 31, 1990"),
    location: "files/newsletters/Volume-2-Issue-09.pdf",
  },
  {
    slug: "volume-2-10",
    visible: true,
    title: "Volume 2 Issue 10",
    author: "Ada Morris",
    publishDate: new Date("September 30, 1990"),
    location: "files/newsletters/Volume-2-Issue-10.pdf",
  },
  {
    slug: "volume-2-11",
    visible: true,
    title: "Volume 2 Issue 11",
    author: "Ada Morris",
    publishDate: new Date("October 31, 1990"),
    location: "files/newsletters/Volume-2-Issue-11.pdf",
  },
  {
    slug: "volume-2-12",
    visible: true,
    title: "Volume 2 Issue 12",
    author: "Ada Morris",
    publishDate: new Date("November 30, 1990"),
    location: "files/newsletters/Volume-2-Issue-12.pdf",
  },
  {
    slug: "volume-2-13",
    visible: true,
    title: "Volume 2 Issue 13",
    author: "Ada Morris",
    publishDate: new Date("December 31, 1990"),
    location: "files/newsletters/Volume-2-Issue-13.pdf",
  },
  {
    slug: "volume-3-1",
    visible: true,
    title: "Volume 3 Issue 1",
    author: "Ada Morris",
    publishDate: new Date("January 31, 1991"),
    location: "files/newsletters/Volume-3-Issue-01.pdf",
  },
  {
    slug: "volume-3-2",
    visible: true,
    title: "Volume 3 Issue 2",
    author: "Ada Morris",
    publishDate: new Date("February 28, 1991"),
    location: "files/newsletters/Volume-3-Issue-02.pdf",
  },
  {
    slug: "volume-3-3",
    visible: true,
    title: "Volume 3 Issue 3",
    author: "Ada Morris",
    publishDate: new Date("March 31, 1991"),
    location: "files/newsletters/Volume-3-Issue-03.pdf",
  },
  {
    slug: "volume-3-4",
    visible: true,
    title: "Volume 3 Issue 4",
    author: "Ada Morris",
    publishDate: new Date("April 30, 1991"),
    location: "files/newsletters/Volume-3-Issue-04.pdf",
  },
  {
    slug: "volume-3-5",
    visible: true,
    title: "Volume 3 Issue 5",
    author: "Ada Morris",
    publishDate: new Date("May 31, 1991"),
    location: "files/newsletters/Volume-3-Issue-05.pdf",
  },
  {
    slug: "volume-3-6",
    visible: true,
    title: "Volume 3 Issue 6",
    author: "Ada Morris",
    publishDate: new Date("June 31, 1991"),
    location: "files/newsletters/Volume-3-Issue-06.pdf",
  },
  {
    slug: "volume-3-7",
    visible: true,
    title: "Volume 3 Issue 7",
    author: "Ada Morris",
    publishDate: new Date("July 31, 1991"),
    location: "files/newsletters/Volume-3-Issue-07.pdf",
  },
  {
    slug: "volume-3-8",
    visible: true,
    title: "Volume 3 Issue 8",
    author: "Ada Morris",
    publishDate: new Date("August 31, 1991"),
    location: "files/newsletters/Volume-3-Issue-08.pdf",
  },
  {
    slug: "volume-3-9",
    visible: true,
    title: "Volume 3 Issue 9",
    author: "Ada Morris",
    publishDate: new Date("September 30, 1991"),
    location: "files/newsletters/Volume-3-Issue-09.pdf",
  },
  {
    slug: "volume-3-10",
    visible: true,
    title: "Volume 3 Issue 10",
    author: "Ada Morris",
    publishDate: new Date("October 31, 1991"),
    location: "files/newsletters/Volume-3-Issue-10.pdf",
  },
  {
    slug: "volume-3-11",
    visible: true,
    title: "Volume 3 Issue 11",
    author: "Ada Morris",
    publishDate: new Date("November 30, 1991"),
    location: "files/newsletters/Volume-3-Issue-11.pdf",
  },
  {
    slug: "volume-3-12",
    visible: true,
    title: "Volume 3 Issue 12",
    author: "Ada Morris",
    publishDate: new Date("December 31, 1991"),
    location: "files/newsletters/Volume-3-Issue-12.pdf",
  },
  {
    slug: "volume-4-1",
    visible: true,
    title: "Volume 4 Issue 1",
    author: "Ada Morris",
    publishDate: new Date("January 31, 1992"),
    location: "files/newsletters/Volume-4-Issue-01.pdf",
  },
  {
    slug: "volume-4-2-3",
    visible: true,
    title: "Volume 4 Issue 2-3",
    author: "Ada Morris",
    publishDate: new Date("March 31, 1992"),
    location: "files/newsletters/Volume-4-Issue-02-and-03.pdf",
  },
  {
    slug: "volume-4-4-5",
    visible: true,
    title: "Volume 4 Issue 4-5",
    author: "Ada Morris",
    publishDate: new Date("May 30, 1992"),
    location: "files/newsletters/Volume-4-Issue-04.pdf",
  },
  {
    slug: "volume-4-6",
    visible: true,
    title: "Volume 4 Issue 6",
    author: "Ada Morris",
    publishDate: new Date("June 30, 1992"),
    location: "files/newsletters/Volume-4-Issue-06.pdf",
  },
  {
    slug: "volume-4-7-8",
    visible: true,
    title: "Volume 4 Issue 7-8",
    author: "Ada Morris",
    publishDate: new Date("August 31, 1992"),
    location: "files/newsletters/Volume-4-Issue-07-and-08.pdf",
  },
  {
    slug: "volume-4-9",
    visible: true,
    title: "Volume 4 Issue 9",
    author: "Ada Morris",
    publishDate: new Date("September 30, 1992"),
    location: "files/newsletters/Volume-4-Issue-09.pdf",
  },
  {
    slug: "volume-4-10",
    visible: true,
    title: "Volume 4 Issue 10",
    author: "Ada Morris",
    publishDate: new Date("October 31, 1992"),
    location: "files/newsletters/Volume-4-Issue-10.pdf",
  },
  {
    slug: "volume-4-11",
    visible: true,
    title: "Volume 4 Issue 11",
    author: "Ada Morris",
    publishDate: new Date("November 30, 1992"),
    location: "files/newsletters/Volume-4-Issue-11.pdf",
  },
  {
    slug: "volume-5-1",
    visible: true,
    title: "Volume 5 Issue 1",
    author: "Ada Morris",
    publishDate: new Date("January 31, 1993"),
    location: "files/newsletters/Volume-5-Issue-01.pdf",
  },
  {
    slug: "volume-5-2",
    visible: true,
    title: "Volume 5 Issue 2",
    author: "Ada Morris",
    publishDate: new Date("February 28, 1993"),
    location: "files/newsletters/Volume-5-Issue-02.pdf",
  },
  {
    slug: "volume-5-3",
    visible: true,
    title: "Volume 5 Issue 3",
    author: "Ada Morris",
    publishDate: new Date("March 31, 1993"),
    location: "files/newsletters/Volume-5-Issue-03.pdf",
  },
  {
    slug: "volume-5-4",
    visible: true,
    title: "Volume 5 Issue 4",
    author: "Ada Morris",
    publishDate: new Date("April 30, 1993"),
    location: "files/newsletters/Volume-5-Issue-04.pdf",
  },
  {
    slug: "volume-5-5",
    visible: true,
    title: "Volume 5 Issue 5",
    author: "Ada Morris",
    publishDate: new Date("May 30, 1993"),
    location: "files/newsletters/Volume-5-Issue-05.pdf",
  },
  {
    slug: "volume-5-6",
    visible: true,
    title: "Volume 5 Issue 6",
    author: "Ada Morris",
    publishDate: new Date("June 30, 1993"),
    location: "files/newsletters/Volume-5-Issue-06.pdf",
  },
  {
    slug: "volume-5-7",
    visible: true,
    title: "Volume 5 Issue 7",
    author: "Ada Morris",
    publishDate: new Date("July 31, 1993"),
    location: "files/newsletters/Volume-5-Issue-07.pdf",
  },
  {
    slug: "volume-5-8-9",
    visible: true,
    title: "Volume 5 Issue 8-9",
    author: "Ada Morris",
    publishDate: new Date("September 30, 1993"),
    location: "files/newsletters/Volume-5-Issue-08-and-09.pdf",
  },
  {
    slug: "volume-5-10",
    visible: true,
    title: "Volume 5 Issue 10",
    author: "Ada Morris",
    publishDate: new Date("October 31, 1993"),
    location: "files/newsletters/Volume-5-Issue-10.pdf",
  },
  {
    slug: "volume-6-1-3",
    visible: true,
    title: "Volume 6 Issue 1-3",
    author: "Ada Morris",
    publishDate: new Date("March 31, 1994"),
    location: "files/newsletters/Volume-6-Issue-02.pdf",
  },
  {
    slug: "volume-6-4-6",
    visible: true,
    title: "Volume 6 Issue 4-6",
    author: "Ada Morris",
    publishDate: new Date("June 30, 1994"),
    location: "files/newsletters/Volume-6-Issue-03.pdf",
  },
  {
    slug: "volume-7-1",
    visible: true,
    title: "Volume 7 Issue 1",
    author: "Rodney Craddock",
    publishDate: new Date("May 31, 2023"),
    location: "files/newsletters/Volume-7-Issue-01.pdf",
  },
  {
    slug: "volume-7-2",
    visible: true,
    title: "Volume 7 Issue 2",
    author: "Lynne McCafferty",
    publishDate: new Date("June 09, 2023"),
    location: "files/newsletters/Volume-7-Issue-02.pdf",
  },
];
