export type newsletter = {
  title: string;
  author: string;
  publishDate: Date;
  location: string;
}

export const newsletters: newsletter[] = [
  {
    title: 'Volume 1 Issue 1',
    author: 'Ada Morris',
    publishDate: new Date('December 12, 1988'),
    location: 'files/newsletters/Volume-1-Issue-01.pdf',
  },
  {
    title: 'Volume 1 Issue 2',
    author: 'Ada Morris',
    publishDate: new Date('January 18, 1989'),
    location: 'files/newsletters/Volume-1-Issue-02.pdf',
  },
  {
    title: 'Volume 1 Issue 3',
    author: 'Ada Morris',
    publishDate: new Date('February 28, 1989'),
    location: 'files/newsletters/Volume-1-Issue-03.pdf',
  },
  {
    title: 'Volume 1 Issue 4',
    author: 'Ada Morris',
    publishDate: new Date('March 31, 1989'),
    location: 'files/newsletters/Volume-1-Issue-04.pdf',
  },
  {
    title: 'Volume 1 Issue 5',
    author: 'Ada Morris',
    publishDate: new Date('April 30, 1989'),
    location: 'files/newsletters/Volume-1-Issue-05.pdf',
  },
  {
    title: 'Volume 1 Issue 6',
    author: 'Ada Morris',
    publishDate: new Date('May 30, 1989'),
    location: 'files/newsletters/Volume-1-Issue-06.pdf',
  },
  {
    title: 'Volume 1 Issue 7',
    author: 'Ada Morris',
    publishDate: new Date('June 31, 1989'),
    location: 'files/newsletters/Volume-1-Issue-07.pdf',
  },
  {
    title: 'Volume 1 Issue 8',
    author: 'Ada Morris',
    publishDate: new Date('July 31, 1989'),
    location: 'files/newsletters/Volume-1-Issue-08.pdf',
  },
  {
    title: 'Volume 1 Issue 9',
    author: 'Ada Morris',
    publishDate: new Date('August 31, 1989'),
    location: 'files/newsletters/Volume-1-Issue-09.pdf',
  },
  {
    title: 'Volume 1 Issue 10',
    author: 'Ada Morris',
    publishDate: new Date('September 31, 1989'),
    location: 'files/newsletters/Volume-1-Issue-10.pdf',
  },
  {
    title: 'Volume 1 Issue 11',
    author: 'Ada Morris',
    publishDate: new Date('October 31, 1989'),
    location: 'files/newsletters/Volume-1-Issue-11.pdf',
  },
  {
    title: 'Volume 1 Issue 12',
    author: 'Ada Morris',
    publishDate: new Date('November 30, 1989'),
    location: 'files/newsletters/Volume-1-Issue-12.pdf',
  },
  {
    title: 'Volume 2 Issue 1',
    author: 'Ada Morris',
    publishDate: new Date('December 31, 1989'),
    location: 'files/newsletters/Volume-2-Issue-01.pdf',
  },
  {
    title: 'Volume 2 Issue 2',
    author: 'Ada Morris',
    publishDate: new Date('January 31, 1990'),
    location: 'files/newsletters/Volume-2-Issue-02.pdf',
  },
  {
    title: 'Volume 2 Issue 3',
    author: 'Ada Morris',
    publishDate: new Date('February 28, 1990'),
    location: 'files/newsletters/Volume-2-Issue-03.pdf',
  },
  {
    title: 'Volume 2 Issue 4',
    author: 'Ada Morris',
    publishDate: new Date('March 31, 1990'),
    location: 'files/newsletters/Volume-2-Issue-04.pdf',
  },
  {
    title: 'Volume 2 Issue 5',
    author: 'Ada Morris',
    publishDate: new Date('April 30, 1990'),
    location: 'files/newsletters/Volume-2-Issue-05.pdf',
  },
  {
    title: 'Volume 2 Issue 6',
    author: 'Ada Morris',
    publishDate: new Date('May 31, 1990'),
    location: 'files/newsletters/Volume-2-Issue-06.pdf',
  },
  {
    title: 'Volume 2 Issue 7',
    author: 'Ada Morris',
    publishDate: new Date('June 30, 1990'),
    location: 'files/newsletters/Volume-2-Issue-07.pdf',
  },
  {
    title: 'Volume 2 Issue 8',
    author: 'Ada Morris',
    publishDate: new Date('July 31, 1990'),
    location: 'files/newsletters/Volume-2-Issue-08.pdf',
  },
  {
    title: 'Volume 2 Issue 9',
    author: 'Ada Morris',
    publishDate: new Date('August 31, 1990'),
    location: 'files/newsletters/Volume-2-Issue-09.pdf',
  },
  {
    title: 'Volume 2 Issue 10',
    author: 'Ada Morris',
    publishDate: new Date('September 30, 1990'),
    location: 'files/newsletters/Volume-2-Issue-10.pdf',
  },
  {
    title: 'Volume 2 Issue 11',
    author: 'Ada Morris',
    publishDate: new Date('October 31, 1990'),
    location: 'files/newsletters/Volume-2-Issue-11.pdf',
  },
  {
    title: 'Volume 2 Issue 12',
    author: 'Ada Morris',
    publishDate: new Date('November 30, 1990'),
    location: 'files/newsletters/Volume-2-Issue-12.pdf',
  },
  {
    title: 'Volume 2 Issue 13',
    author: 'Ada Morris',
    publishDate: new Date('December 31, 1990'),
    location: 'files/newsletters/Volume-2-Issue-13.pdf',
  },
  {
    title: 'Volume 3 Issue 1',
    author: 'Ada Morris',
    publishDate: new Date('January 31, 1991'),
    location: 'files/newsletters/Volume-3-Issue-01.pdf',
  },
  {
    title: 'Volume 3 Issue 2',
    author: 'Ada Morris',
    publishDate: new Date('February 28, 1991'),
    location: 'files/newsletters/Volume-3-Issue-02.pdf',
  },
  {
    title: 'Volume 3 Issue 3',
    author: 'Ada Morris',
    publishDate: new Date('March 31, 1991'),
    location: 'files/newsletters/Volume-3-Issue-03.pdf',
  },
  {
    title: 'Volume 3 Issue 4',
    author: 'Ada Morris',
    publishDate: new Date('April 30, 1991'),
    location: 'files/newsletters/Volume-3-Issue-04.pdf',
  },
  {
    title: 'Volume 3 Issue 5',
    author: 'Ada Morris',
    publishDate: new Date('May 31, 1991'),
    location: 'files/newsletters/Volume-3-Issue-05.pdf',
  },
  {
    title: 'Volume 3 Issue 6',
    author: 'Ada Morris',
    publishDate: new Date('June 31, 1991'),
    location: 'files/newsletters/Volume-3-Issue-06.pdf',
  },
  {
    title: 'Volume 3 Issue 7',
    author: 'Ada Morris',
    publishDate: new Date('July 31, 1991'),
    location: 'files/newsletters/Volume-3-Issue-07.pdf',
  },
  {
    title: 'Volume 3 Issue 8',
    author: 'Ada Morris',
    publishDate: new Date('August 31, 1991'),
    location: 'files/newsletters/Volume-3-Issue-08.pdf',
  },
  {
    title: 'Volume 3 Issue 9',
    author: 'Ada Morris',
    publishDate: new Date('September 30, 1991'),
    location: 'files/newsletters/Volume-3-Issue-09.pdf',
  },
  {
    title: 'Volume 3 Issue 10',
    author: 'Ada Morris',
    publishDate: new Date('October 31, 1991'),
    location: 'files/newsletters/Volume-3-Issue-10.pdf',
  },
  {
    title: 'Volume 3 Issue 11',
    author: 'Ada Morris',
    publishDate: new Date('November 30, 1991'),
    location: 'files/newsletters/Volume-3-Issue-11.pdf',
  },
  {
    title: 'Volume 3 Issue 12',
    author: 'Ada Morris',
    publishDate: new Date('December 31, 1991'),
    location: 'files/newsletters/Volume-3-Issue-12.pdf',
  },
  {
    title: 'Volume 4 Issue 1',
    author: 'Ada Morris',
    publishDate: new Date('January 31, 1992'),
    location: 'files/newsletters/Volume-4-Issue-01.pdf',
  },
  {
    title: 'Volume 4 Issue 2-3',
    author: 'Ada Morris',
    publishDate: new Date('March 31, 1992'),
    location: 'files/newsletters/Volume-4-Issue-02-and-03.pdf',
  },
  {
    title: 'Volume 4 Issue 4-5',
    author: 'Ada Morris',
    publishDate: new Date('May 30, 1992'),
    location: 'files/newsletters/Volume-4-Issue-04.pdf',
  },
  {
    title: 'Volume 4 Issue 6',
    author: 'Ada Morris',
    publishDate: new Date('June 30, 1992'),
    location: 'files/newsletters/Volume-4-Issue-06.pdf',
  },
  {
    title: 'Volume 4 Issue 7-8',
    author: 'Ada Morris',
    publishDate: new Date('August 31, 1992'),
    location: 'files/newsletters/Volume-4-Issue-07-and-08.pdf',
  },
  {
    title: 'Volume 4 Issue 9',
    author: 'Ada Morris',
    publishDate: new Date('September 30, 1992'),
    location: 'files/newsletters/Volume-4-Issue-09.pdf',
  },
  {
    title: 'Volume 4 Issue 10',
    author: 'Ada Morris',
    publishDate: new Date('October 31, 1992'),
    location: 'files/newsletters/Volume-4-Issue-10.pdf',
  },
  {
    title: 'Volume 4 Issue 11',
    author: 'Ada Morris',
    publishDate: new Date('November 30, 1992'),
    location: 'files/newsletters/Volume-4-Issue-11.pdf',
  },
  {
    title: 'Volume 5 Issue 1',
    author: 'Ada Morris',
    publishDate: new Date('January 31, 1993'),
    location: 'files/newsletters/Volume-5-Issue-01.pdf',
  },
  {
    title: 'Volume 5 Issue 2',
    author: 'Ada Morris',
    publishDate: new Date('February 28, 1993'),
    location: 'files/newsletters/Volume-5-Issue-02.pdf',
  },
  {
    title: 'Volume 5 Issue 3',
    author: 'Ada Morris',
    publishDate: new Date('March 31, 1993'),
    location: 'files/newsletters/Volume-5-Issue-03.pdf',
  },
  {
    title: 'Volume 5 Issue 4',
    author: 'Ada Morris',
    publishDate: new Date('April 30, 1993'),
    location: 'files/newsletters/Volume-5-Issue-04.pdf',
  },
  {
    title: 'Volume 5 Issue 5',
    author: 'Ada Morris',
    publishDate: new Date('May 30, 1993'),
    location: 'files/newsletters/Volume-5-Issue-05.pdf',
  },
  {
    title: 'Volume 5 Issue 6',
    author: 'Ada Morris',
    publishDate: new Date('June 30, 1993'),
    location: 'files/newsletters/Volume-5-Issue-06.pdf',
  },
  {
    title: 'Volume 5 Issue 7',
    author: 'Ada Morris',
    publishDate: new Date('July 31, 1993'),
    location: 'files/newsletters/Volume-5-Issue-07.pdf',
  },
  {
    title: 'Volume 5 Issue 8-9',
    author: 'Ada Morris',
    publishDate: new Date('September 30, 1993'),
    location: 'files/newsletters/Volume-5-Issue-08-and-09.pdf',
  },
  {
    title: 'Volume 5 Issue 10',
    author: 'Ada Morris',
    publishDate: new Date('October 31, 1993'),
    location: 'files/newsletters/Volume-5-Issue-10.pdf',
  },
  {
    title: 'Volume 6 Issue 1-3',
    author: 'Ada Morris',
    publishDate: new Date('March 31, 1994'),
    location: 'files/newsletters/Volume-6-Issue-02.pdf',
  },
  {
    title: 'Volume 6 Issue 4-6',
    author: 'Ada Morris',
    publishDate: new Date('June 30, 1994'),
    location: 'files/newsletters/Volume-6-Issue-03.pdf',
  },
  { 
    title: 'May 2023 - Volume 1',
    author: 'Rodney Craddock',
    publishDate: new Date('May 31, 2023'),
    location: 'files/newsletters/May-2023-Volume-1.pdf',
  }

]
