name: Build and Deploy Craddock Connection website

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build Astro.js project
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Specify your AWS region

      - name: Install SAM CLI
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/aws/aws-sam-cli/develop/installer/pyinstaller/install)" && sam --version

      - name: Sync Website Content to S3
        run: aws s3 sync ./dist s3://${{ secrets.S3_BUCKET_NAME }} --delete

      - name: Package SAM Application
        run: sam package --template-file template.yaml --output-template-file packaged.yaml --s3-bucket ${{ secrets.S3_BUCKET_NAME }}

      - name: Deploy SAM Application
        run: sam deploy --template-file packaged.yaml --stack-name craddock-org-stack --capabilities CAPABILITY_IAM --no-fail-on-empty-changeset

      - name: Cleanup Artifacts
        run: rm -rf packaged.yaml
